# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - dquintil-bootcamp

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn install #-Dmaven.test.skip=true

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dquintil-bootcamp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_62ab3f807a624f0880887a23c2944358 }}
        package: '${{ github.workspace }}/target/*.jar'
